CMakeLists.txt: respect libdir setting
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/665168

ERROR: QA Issue: lib32-com.webos.service.mediaindexer: Files/directories were installed but not shipped in any package:
  /usr/lib/libmediaindexerclient.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-com.webos.service.mediaindexer: 1 installed and not shipped files. [installed-vs-shipped]

when libdir is /usr/lib32 or /usr/lib64.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-20118] Bitbake world issues 2023-07
[WRP-24156] CCC: Various build fixes

Change-Id: I92a08e166b92d8a34afa575704b77a6b88714cce
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.mediaindexer/+/365247
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Tested-by: Myonggu Lee <myonggu.lee@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Myonggu Lee <myonggu.lee@lge.com>