Refactor rescan and fix some warnings occurred when putting json messages
:Release Notes:
Refactor rescan and fix some warnings occurred
when putting json messages

:Detailed Notes:
1. In rescan procedure, dirty count has been introduced
and unflagDirtyAudioCount_, unflagDirtyVideoCount_,
unflagDirtyImageCount_ has been deprecated for refactoring.

2. Fix following warnings shown whenever creating batch command.
PBNJSON src/pbnjson_c/jobject.c:1151 :: Error in object hierarchy.
Inserting jvalue would create an illegal cyclic dependency

:Testing Performed:
Tested with webos Auto

:QA Notes:

:Issues Addressed:
[PLAT-131022] [Performance Improvement] Fix warnings in
              rescan procedure

Change-Id: I61b0662015f09cd47ccdb9691e3ff920dd622410
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.mediaindexer/+/300478
Tested-by: <ejihoon.lee@lge.com>
Reviewed-by: <ejihoon.lee@lge.com>